# Generated by Django 6.0.6 on 2026-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('query_accuracy', 'Query Accuracy'), ('avg_response_time', 'Avg Response Time'), ('monthly_active_users', 'Monthly Active Users'), ('query_growth', 'Query Growth'), ('queries', 'AI Queries'), ('uploads', 'Uploads'), ('department_usage', 'Department Usage')], max_length=40)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('period', models.CharField(default='current', max_length=20)),
                ('dimension', models.CharField(blank=True, default='', max_length=100)),
                ('delta_label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
                'db_table': 'analytics_metrics',
                'ordering': ['metric_name', 'period'],
                'indexes': [models.Index(fields=['metric_name', 'period'], name='analytics_m_metric__5de8fb_idx')],
            },
        ),
    ]
