# Generated by Django 6.0.6 on 2026-07-04 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(default='mock-assistant-v1', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session_id'], name='ai_conversa_session_687709_idx'), models.Index(fields=['-timestamp'], name='ai_conversa_timesta_217f43_idx')],
            },
        ),
    ]
