# Generated by Django 6.0.6 on 2026-07-04 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Degraded', 'Degraded'), ('Down', 'Down')], default='Operational', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Latest observed latency in milliseconds')),
                ('uptime_percentage', models.DecimalField(decimal_places=2, default=99.9, max_digits=5)),
                ('health_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System statuses',
                'db_table': 'system_status',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Document Upload'), ('query_resolved', 'AI Query Resolved'), ('report_generated', 'Report Generated'), ('document_indexed', 'Document Indexed'), ('login', 'User Login'), ('other', 'Other')], default='other', max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activities_timesta_bede49_idx')],
            },
        ),
    ]
