# Generated by Django 6.0.6 on 2026-07-04 07:05

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'TXT'), ('xlsx', 'XLSX')], max_length=10)),
                ('size', models.PositiveBigIntegerField(help_text='Size in bytes')),
                ('category', models.CharField(choices=[('manual', 'Manual'), ('sop', 'SOP'), ('inspection_report', 'Inspection Report'), ('safety', 'Safety'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=30)),
                ('processing_status', models.CharField(choices=[('queued', 'Queued'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='queued', max_length=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['-upload_date'], name='documents_upload__4ed938_idx'), models.Index(fields=['processing_status'], name='documents_process_e1e618_idx'), models.Index(fields=['category'], name='documents_categor_f8ad6f_idx')],
            },
        ),
    ]
