import io

from django.core.files.base import ContentFile
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from .models import Report, ReportStatus


def generate_report_pdf(report: Report) -> Report:
    """Render a simple PDF for the given Report and attach it to `report.file`."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=2 * cm, bottomMargin=2 * cm, leftMargin=2 * cm, rightMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    story = [
        Paragraph('INDUSMIND AI — Industrial Knowledge Intelligence Platform', styles['Heading2']),
        Spacer(1, 0.3 * cm),
        Paragraph(report.title, styles['Title']),
        Spacer(1, 0.5 * cm),
    ]

    meta_table = Table(
        [
            ['Reference', report.reference],
            ['Type', report.report_type],
            ['Generated By', report.generated_by.name],
            ['Generated At', report.generated_at.strftime('%Y-%m-%d %H:%M')],
        ],
        colWidths=[4 * cm, 10 * cm],
    )
    meta_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#D0D5DD')),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F2F4F7')),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.8 * cm))

    story.append(Paragraph('Summary', styles['Heading3']))
    story.append(Paragraph(
        report.summary or 'This report was auto-generated by INDUSMIND AI based on current '
                          'platform activity, indexed documents, and AI assistant usage.',
        styles['BodyText'],
    ))

    doc.build(story)
    buffer.seek(0)

    filename = f'{report.reference}.pdf'
    report.file.save(filename, ContentFile(buffer.read()), save=False)
    report.status = ReportStatus.READY
    report.save(update_fields=['file', 'status', 'updated_at'])
    return report
